// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ShillCore$Type } from "./ShillCore";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ShillCore"]: ShillCore$Type;
    ["contracts/ShillCore.sol:ShillCore"]: ShillCore$Type;
  }

  interface ContractTypesMap {
    ["ShillCore"]: GetContractReturnType<ShillCore$Type["abi"]>;
    ["contracts/ShillCore.sol:ShillCore"]: GetContractReturnType<ShillCore$Type["abi"]>;
  }
}
