// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Token$Type } from "./Token";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Token"]: Token$Type;
    ["contracts/Token.sol:Token"]: Token$Type;
  }

  interface ContractTypesMap {
    ["Token"]: GetContractReturnType<Token$Type["abi"]>;
    ["contracts/Token.sol:Token"]: GetContractReturnType<Token$Type["abi"]>;
  }
}
